# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dan's Tech Blog
email: heintzelman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my new blog site! Included are all of my posts that I have written while attending Chicago Dev Bootcamp.
baseurl: "/dans-tech-blog" # the subpath of your site, e.g. /blog
url: "http://Heintzdm.github.io/dans-tech-blog" # the base hostname & protocol for your site
github_username:  Heintzdm

# Build settings
markdown: kramdown
